=== df9ry/FreeAX25/FreeAX25.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    Project FreeAX25
    Copyright (C) 2015  tania@df9ry.de

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:tp="http://df9ry.ampr.org/FreeAX25/Config"
        targetNamespace="http://df9ry.ampr.org/FreeAX25/Config" 
        elementFormDefault="qualified">
    
    <!-- The root element always have to be a Configuration -->    
    <xs:element name="Configuration" type="tp:ConfigurationType"/>
       
    <!-- A Configuration has Settings and Plugins -->   
    <xs:complexType name="ConfigurationType">
    	<xs:sequence>
    		<xs:element name="Settings" type="tp:SettingsType"
    			minOccurs="0" maxOccurs="1">
    			<xs:unique name="ConfigurationSettingsUnique">
    				<xs:selector xpath="tp:Setting"/>
    				<xs:field xpath="@name"/>
    			</xs:unique>
    		</xs:element>
    		<xs:element name="Plugins" type="tp:PluginsType"
    			minOccurs="0" maxOccurs="1">
    			<xs:unique name="ConfigurationPluginsUnique">
    				<xs:selector xpath="tp:Plugin"/>
    				<xs:field xpath="@name"/>
    			</xs:unique>
    		</xs:element>
    	</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required"/>
    </xs:complexType>
    
    <!-- List of Plugins -->
    <xs:complexType name="PluginsType">
    	<xs:sequence>
    		<xs:element name="Plugin" type="tp:PluginType"
    			minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <!--
    	A Plugin has a name and optionally a file to load the
    	Plugin from. If no file is specified this is a builtin
    	Plugin. It can have any number of Settings.
    	A Plugin can instantiate any number of instances.
    -->
    <xs:complexType name="PluginType">
    	<xs:sequence>
    		<xs:element name="Settings" type="tp:SettingsType"
    			minOccurs="0" maxOccurs="1">
    			<xs:unique name="PluginSettingsUnique">
    				<xs:selector xpath="tp:Setting"/>
    				<xs:field xpath="@name"/>
    			</xs:unique>
    		</xs:element>
    		<xs:element name="Instances" type="tp:InstancesType"
    			minOccurs="0" maxOccurs="1">
    			<xs:unique name="PluginInstancesUnique">
    				<xs:selector xpath="tp:Instance"/>
    				<xs:field xpath="@name"/>
    			</xs:unique>
    		</xs:element>
    	</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required"/>
		<xs:attribute name="file" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <!-- List of Settings -->
    <xs:complexType name="SettingsType">
    	<xs:sequence>
    		<xs:element name="Setting" type="tp:SettingType"
    			minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <!-- Every Setting has a name and a value (text-node) -->
    <xs:complexType name="SettingType">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    
    <!-- List of Instances -->
    <xs:complexType name="InstancesType">
    	<xs:sequence>
    		<xs:element name="Instance" type="tp:InstanceType"
    			minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>

	<!--
		An Instance is a concrete realisation of a Plugin. Every
		Instance have to have a unique name and can have any number
		of Settings.
	-->    
    <xs:complexType name="InstanceType">
    	<xs:sequence>
    		<xs:element name="Settings" type="tp:SettingsType"
    			minOccurs="0" maxOccurs="1">
    			<xs:unique name="InstanceSettingsUnique">
    				<xs:selector xpath="tp:Setting"/>
    				<xs:field xpath="@name"/>
    			</xs:unique>
    		</xs:element>
    	</xs:sequence>
		<xs:attribute name="name" type="xs:Name" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== df9ry/FreeAX25/FreeAX25.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Project FreeAX25
    Copyright (C) 2015  tania@df9ry.de

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<Configuration name="Default"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://df9ry.ampr.org/FreeAX25/Config FreeAX25.xsd" 
	xmlns="http://df9ry.ampr.org/FreeAX25/Config">
	
	<Settings>
	</Settings>
	
	<Plugins>

		<!-- Builtin logger -->
		<Plugin name="_LOGGER">
			<Settings>
				<!-- NONE, ERROR, WARNING, INFO, DEBUG -->
				<Setting name="level">DEBUG</Setting>
			</Settings>
		</Plugin>
		
		<!-- Builtin timer -->
		<Plugin name="_TIMER">
			<Settings>
				<!-- Timer tick in ms -->
				<Setting name="tick">20</Setting>
			</Settings>
		</Plugin>
		
		<!-- Builtin null object -->
		<Plugin name="_NULL">
			<Instances>
				<Instance name="null">
					<ServerEndPoint name="downlink" url="channel:null"/>
				</Instance>
			</Instances>
		</Plugin>
		
	</Plugins>
	
</Configuration>
